### ISSUE TITLE
Allow specifying/renaming of database

### ISSUE THREAD

**Issue by lazyatom** [dokku/dokku-redis#137]
I believe a recent change had the plugin expect that the service name and the database names are identical, whereas earlier versions did not. For example:

* with the earlier plugin, `dokku postgres:create my-app-database` would create a service called `my-add-database` containing a database `my_app_database`
* with the new plugin, `dokku postgres:export my-app-database` _tries_ to export a database called `my-app-database`, but that database doesn't exist.

We should figure out a way to either:

* rename and re-link the database inside the service
* rename the service itself (`dokku postgres:rename <old-service-name> <new-service-name>` maybe?)
* allow some way to specify the internal service database name

... such that older postgres services can be made compatible with the current mechanics of the plugin.

**Comment by josegonzalez** [comment]
For anyone that lands on this issue, the correct fix is to do write the correct database name into the `DATABASE_NAME` file in the service root (you can get that from `$SERVICE:info`). 

Rather than expose the internals in a potentially dangerous way (folks will assume it will rename the database, which you can't...), we'll close this for now as this issue is a bit old so it shouldn't impact most of our existing users.

**Comment by josegonzalez** [comment]
If you're still seeing this issue, feel free to comment or open a new ticket and I'll reconsider.

**Comment by gamedevsam** [comment]
I just ran into wanting to do this... I'm looking at potentially creating a new DB, exporting the old one and re-creating it from a copy. I can do this because my DB is small, but it's still a lot of effort for a small fix.

Is this a trivial ask to rename service / DB? Or would this be a lot of work (I'm asking as a total newb here).
