### ISSUE TITLE
FATAL CONFIG FILE ERROR: Bad directive or wrong number of arguments

### ISSUE THREAD

**Issue by baptisteArno** [dokku/dokku-redis#165]
When creating a redis service with this command:

```
dokku redis:create posthog -I 6-alpine
```

It won't connect and when displaying the logs it says:

```
*** FATAL CONFIG FILE ERROR (Redis 6.2.4) ***
Reading the configuration file, at line 1
>>> '404: Not Found'
Bad directive or wrong number of arguments
```

**Comment by josegonzalez** [comment]
That is caused by this: https://github.com/dokku/dokku-redis/blob/master/functions#L50

You'll need to download the correct redis config file and set `REDIS_CONFIG_PATH` to the path on disk to it before creating the redis install if you want to use an alternative image.

Is there a reason the default image is not good?

**Comment by baptisteArno** [comment]
Thank you for the clarification!

I want to deploy [PostHog](https://github.com/PostHog/posthog) on Dokku so I'm referring to their `docker-compose` and it uses the `6-alpine` image. But I guess the default will still work so I'm going to try this out 👍
