### ISSUE TITLE
REDIS_URL contains username but user not set in redis instance

### ISSUE THREAD

**Issue by nicolas-brousse** [dokku/dokku-redis#170]
## Description of problem

I recently see the following warning on a Rails application hosted in one of our dokku servers.

`The Redis connection was configured with username "typofonderie-staging_worker", but the provided password was for the default user. This will start failing in redis-rb 4.6.` 

### How reproducible

Having a rails application that use `redis` `4.5.1+` gem. And use `REDIS_URL` env var for connection.

#### Actual Results

Warning error: `The Redis connection was configured with username "typofonderie-staging_worker", but the provided password was for the default user. This will start failing in redis-rb 4.6.`

This message is set by the [following code](https://github.com/redis/redis-rb/blob/0c8e5d0ae2b2bbd9799f9897bd74310a616b3188/lib/redis/client.rb#L116-L142).

#### Expected Results

Not having error message

### Additional information

I don't give more additional information I don't think it is relevant for this issue. But if it is then I will give more information.

## Ideas to resolve issue
I guess there is two way to improve this:
1. Removing username from `REDIS_URL` and only pass password.
2. Update container creation to create the user

**Comment by josegonzalez** [comment]
Can you include *all* of the information we ask for in our [issue template](https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md)? It is helpful for debugging problems. Thanks.

---

> I don't give more additional information I don't think it is relevant for this issue. But if it is then I will give more information.

Please don't do this in the future. I'm not asking for this information for my health, it is quite literally to debug your issue.

By way of example, we don't [currently set a user](https://github.com/dokku/dokku-redis/blob/master/functions#L179) in the 
`REDIS_URL` - and this was [fixed last February](https://github.com/dokku/dokku-redis/issues/155) - but because you made a decision to omit any debugging details, I don't know if that is your problem.

**Comment by nicolas-brousse** [comment]
> Please don't do this in the future. I'm not asking for this information for my health, it is quite literally to debug your issue.

Ok sorry. I'll take care of this on my future issues.

Sorry also to haven't found the issue you linked here, I did some search but not enough.

Thank you for your response and your time. I'll close this issue.

**Comment by josegonzalez** [comment]
BTW, I believe your fix is to update the dokku-redis plugin and unlink/relink the redis datastore (which may require a dance of some sort depending on what your app uses it for).

**Comment by nicolas-brousse** [comment]
Yes. Thank you for this precision. It's what I'll do on our applications. I didn't notice this change on the plugin.
